/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author José Santes
 */
public class ExamplePage extends javax.swing.JFrame {

    /**
     * Creates new form ExamplePage
     */
    public ExamplePage() {
        initComponents();
    }

    String optionCmbBox;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        cmbCalculo = new javax.swing.JComboBox<>();
        lblCalcular = new javax.swing.JLabel();
        lblFirstVariable = new javax.swing.JLabel();
        lblSecondVariable = new javax.swing.JLabel();
        txtFirstVariable = new javax.swing.JTextField();
        txtSecondVariable = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ley de ohm - ejemplo");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ohm.png"))); // NOI18N

        cmbCalculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intensidad", "Voltaje", "Resistencia" }));
        cmbCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalculoActionPerformed(evt);
            }
        });

        lblCalcular.setText("Calcular");

        lblFirstVariable.setText("Voltaje");

        lblSecondVariable.setText("Resistencia");

        txtResult.setEditable(false);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCalcular)
                    .addComponent(lblSecondVariable, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(lblFirstVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResult)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmbCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFirstVariable)
                    .addComponent(txtSecondVariable))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCalcular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstVariable)
                            .addComponent(txtFirstVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSecondVariable)
                            .addComponent(txtSecondVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular)))
                    .addComponent(lblImage))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        optionCmbBox = cmbCalculo.getSelectedItem().toString();
        double firstVariable = Double.parseDouble(txtFirstVariable.getText());
        double secondVariable = Double.parseDouble(txtSecondVariable.getText());
        Double result;
        switch (optionCmbBox) {
            case "Intensidad" -> result = calcularIntensidad(firstVariable, secondVariable);
            case "Resistencia" -> result = calcularResistencia(firstVariable, secondVariable);
            case "Voltaje" -> result = calcularVoltaje(firstVariable, secondVariable);
            default -> throw new AssertionError();
        }
        txtResult.setText(result.toString());
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void cmbCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalculoActionPerformed
        changeControlTexts();
    }//GEN-LAST:event_cmbCalculoActionPerformed

    private void changeControlTexts() throws AssertionError {
        // TODO add your handling code here:
        optionCmbBox = cmbCalculo.getSelectedItem().toString();
        switch (optionCmbBox) {
            case "Intensidad" -> {
                lblFirstVariable.setText("Voltaje");
                lblSecondVariable.setText("Resistencia");
            }
            case "Resistencia" -> {
                lblFirstVariable.setText("Voltaje");
                lblSecondVariable.setText("Intensidad");
            }
            case "Voltaje" -> {
                lblFirstVariable.setText("Intensidad");
                lblSecondVariable.setText("Resistencia");
            }
            default -> throw new AssertionError();
        }
    }

    private double calcularResistencia(double voltaje, double intensidad) {
        return voltaje / intensidad;
    }

    private double calcularVoltaje(double intensidad, double resistencia) {
        return intensidad*resistencia;
    }

    private double calcularIntensidad(double voltaje, double resitencia) {
        return voltaje/resitencia;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamplePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamplePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbCalculo;
    private javax.swing.JLabel lblCalcular;
    private javax.swing.JLabel lblFirstVariable;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSecondVariable;
    private javax.swing.JTextField txtFirstVariable;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSecondVariable;
    // End of variables declaration//GEN-END:variables
}
